Move deploy to QA after deploy to prod
sul-dlss/DeveloperPlaybook pull request #188
Opened 2022-08-01 20:00 UTC by jcoyne

Deploying to QA is less important than getting the changes out earlier in the day, which leaves more time for troubleshooting in case something goes wrong.  The only reason we really need a QA deploy is to reset the environment. It has no urgency.

2022-08-01 20:01 UTC, justinlittman approved these changes

2022-08-01 20:01 UTC, mjgiarlo approved these changes

2022-08-01 20:04 UTC, ndushay requested changes

2022-08-01 20:04 UTC, ndushay commented on infrateam_first_responder.md
>  Finally, **warn #dlss-infra-chg-mgmt** of the impending deployment to prod, and then deploy the tag you created above to prod using `sdr-deploy`.
it's not "Finally" any more.

2022-08-01 20:36 UTC, jcoyne commented on infrateam_first_responder.md
>  Finally, **warn #dlss-infra-chg-mgmt** of the impending deployment to prod, and then deploy the tag you created above to prod using `sdr-deploy`.
```suggestion
**Warn #dlss-infra-chg-mgmt** of the impending deployment to prod, and then deploy the tag you created above to prod using `sdr-deploy`.
```

2022-08-01 20:36 UTC, jcoyne commented on infrateam_first_responder.md
>  Finally, **warn #dlss-infra-chg-mgmt** of the impending deployment to prod, and then deploy the tag you created above to prod using `sdr-deploy`.
Thanks, fixed that.

2022-08-02 14:10 UTC, lwrubel commented on infrateam_first_responder.md
>  Next, **turn off Google Books when deploying to production** at https://sul-gbooks-prod.stanford.edu/features. This avoids failed deposit due to a temporary Cocina model mismatch. Unlike other applic
This should happen *before* the deploy step in the previous paragraph. It was confusing before, may as well fix now.

2022-08-02 14:10 UTC, lwrubel approved these changes

2022-08-02 16:27 UTC, ndushay requested changes

2022-08-02 16:27 UTC, ndushay commented on infrateam_first_responder.md
> +**Warn #dlss-infra-chg-mgmt** of the impending deployment to prod, and then deploy the tag you created above to prod using `sdr-deploy`.
agree with Laura about splitting this sentence so the actual deploy is AFTER google books is turned on.

2022-08-03 16:09 UTC, ndushay approved these changes

2022-08-03 16:09 UTC, merged