Update infrateam_first_responder.md
sul-dlss/DeveloperPlaybook pull request #189
Opened 2022-08-03 16:14 UTC by ndushay

Tweaking it to make deploy instructions more Naomi-brain-dead proof.

2022-08-03 16:16 UTC, mjgiarlo approved these changes

2022-08-03 16:18 UTC, aaron-collier approved these changes

2022-08-03 16:23 UTC, justinlittman requested changes

2022-08-03 16:23 UTC, justinlittman commented on infrateam_first_responder.md
> +Firt, **warn #dlss-infra-chg-mgmt** of the impending deployment to prod.
"First"

2022-08-03 16:40 UTC, ndushay commented on infrateam_first_responder.md
> +Firt, **warn #dlss-infra-chg-mgmt** of the impending deployment to prod.
Fixed.

2022-08-03 22:58 UTC, jmartin-sul approved these changes

2022-08-05 15:36 UTC, ndushay commented
@justinlittman care to merge this now I've fixed the typo?

2022-08-05 16:16 UTC, justinlittman approved these changes

2022-08-05 16:16 UTC, merged