Add an article about writing good tickets
sul-dlss/DeveloperPlaybook pull request #200
Opened 2022-11-08 13:48 UTC by jcoyne

2022-11-08 14:04 UTC, corylown requested changes
This is a good addition to the playbook

2022-11-08 14:12 UTC, corylown approved these changes

2022-12-01 18:57 UTC, aaron-collier approved these changes

2022-12-01 19:00 UTC, mjgiarlo approved these changes

2022-12-01 19:00 UTC, merged